groups:
  - name: eventsphere.rules
    rules:
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(event_execution_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for operation {{ $labels.operation }}"

      - alert: HighErrorRate
        expr: rate(event_errors_total[5m]) > 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors/sec for operation {{ $labels.operation }}"

      - alert: DatabaseSlowQueries
        expr: rate(event_database_operations_seconds_sum[5m]) / rate(event_database_operations_seconds_count[5m]) > 1
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "Average database query time is {{ $value }}s for operation {{ $labels.operation }}"

      - alert: HighMemoryUsage
        expr: (jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"}) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "JVM heap memory usage is {{ $value | humanizePercentage }}"

      - alert: HighCPUUsage
        expr: system_cpu_usage > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "System CPU usage is {{ $value | humanizePercentage }}"

      - alert: ServiceDown
        expr: up{job="eventsphere"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "EventSphere service is down"
          description: "EventSphere application is not responding"

      - alert: TooManySlowOperations
        expr: increase(event_slow_operations_total[10m]) > 50
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Too many slow operations"
          description: "{{ $value }} slow operations detected in the last 10 minutes for {{ $labels.operation }}"
