name: Build & Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/eventsphere:latest \
            .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/eventsphere:latest

  deploy:
    name: Deploy on EC2 (self-hosted runner)
    runs-on: self-hosted
    needs: build
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Pull & run latest container
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/eventsphere:latest
          docker stop eventsphere || true
          docker rm   eventsphere || true
          # Expose container port 8080 on host port 80
          docker run -d \
            --name eventsphere \
            -p 80:8080 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/eventsphere:latest
